service: lambda-feedback

frameworkVersion: '3'

provider:
  name: aws
  runtime: java25
  region: us-east-2
  httpApi:
    authorizers:
      lambdaAuthorizer:
        type: request
        functionName: lambda-authorizer

  environment:
    SNS_TOPIC_ARN:
      Ref: FeedbackCriticoTopic
    TARGET_FUNCTION_NAME: "arn:aws:lambda:us-east-2:990773979941:function:lambda-armazena-feedback-dev-armazenaFeedback"

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - sns:Publish
          Resource:
            Ref: FeedbackCriticoTopic
        - Effect: Allow
          Action:
            - lambda:InvokeFunction
          Resource:
            - "arn:aws:lambda:us-east-2:990773979941:function:lambda-armazena-feedback-dev-armazenaFeedback"

package:
  artifact: target/function.zip

functions:
  feedback:
    handler: io.quarkus.amazon.lambda.runtime.QuarkusStreamHandler::handleRequest
    events:
      - httpApi:
          path: /avaliacao
          method: post
          authorizer:
            name: lambdaAuthorizer

resources:
  Resources:
    FeedbackCriticoTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: feedback-critico

    FeedbackEmailSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        TopicArn:
          Ref: FeedbackCriticoTopic
        Protocol: email
        Endpoint: RM368441@fiap.com.br