service: lambda

frameworkVersion: '3'

provider:
  name: aws
  runtime: java25
  region: us-east-2

package:
  artifact: target/function.zip

functions:
  armazenaFeedback:
    handler: io.quarkus.amazon.lambda.runtime.QuarkusStreamHandler::handleRequest